# Generated by Django 2.2.5 on 2019-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedy', '0003_auto_20190918_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
